# 下载目录
dir=/home/wx/Downloads

# 支持断点续传
continue=true

# RPC
enable-rpc=true
rpc-listen-all=false
rpc-listen-port=6800
rpc-allow-origin-all=true

# RPC 密钥
rpc-secret=ajfop98q23h78h

# 下载参数
max-concurrent-downloads=5
split=8
max-connection-per-server=8
min-split-size=4M
